### ISSUE TITLE
Extend to multiple searches?

### ISSUE THREAD

**Issue by robitalec** [r-assist/errorist#7]
Right now, it seems `errorist` just searches for the first warning or message.
This came up for me in trying out the package, I was actually more interested in the search results for the second warning..  

---

Reproducible example:

```r
library(errorist)

warn2 <- function() {
  warning('warning one')
  warning('warning two')
}

warn2()
```

**Comment by coatless** [comment]
@robitalec yes, only searching the first error and warning for the latest function call is accurate.   

Having said this, there are two parts here that are drastically different: `error` and `warning`. 

Error-wise, it isn't possible to have two **errors** back-to-back within code execution since the code is exited once a single error is detected. We're able to then use the error handler to trigger an appropriate dispatch. 

Warning dispatch is another story.  `errorist` was setup to search the **first** warning returned as multiple identical warnings may occur in a single function call. Though, this might have been slightly too conservative. Potentially, we could trigger a search on distinct warnings by parsing `names(list.warning)`. 

Self-note: 
https://github.com/r-assist/errorist/blob/8a41cb8be894470cc03aa6b0b1a953018ab3be1b/R/handlers.R#L88-L96

**Comment by robitalec** [comment]
Thanks @coatless!
Silly mistake - you never get two errors. Wrote this up a bit quickly clearly, edited above..

Yes - I think we definitely wouldn't want repeated searches from the same warning repeated, but might be useful to search for unique ones, like you say. Thanks!

**Comment by coatless** [comment]
@robitalec searching multiple warnings should now work. Please try it out in the development version:

```r
remotes::install_github('r-assist/errorist')
```

**Comment by robitalec** [comment]
Perfect! That worked @coatless. 
Thank you.
